# Generated by Django 2.0.4 on 2018-12-05 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('itens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserPlayer')),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('reward_xp', models.IntegerField()),
                ('reward_score', models.IntegerField()),
                ('time_beg', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('url', models.URLField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserPlayer')),
                ('reward_iten', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='itens.Iten')),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='quest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quests.Quest'),
        ),
    ]
